/** @type {import('@lume/cli/config/getUserConfig.js').UserConfig} */
module.exports = {
	importMap: {
		imports: {
			'@babel/runtime/helpers/extends': '/node_modules/@babel/runtime/helpers/esm/extends.js',
			'@codemirror/autocomplete': '/node_modules/@codemirror/autocomplete/dist/index.js',
			'@codemirror/commands': '/node_modules/@codemirror/commands/dist/index.js',
			'@codemirror/lang-css': '/node_modules/@codemirror/lang-css/dist/index.js',
			'@codemirror/lang-html': '/node_modules/@codemirror/lang-html/dist/index.js',
			'@codemirror/lang-javascript': '/node_modules/@codemirror/lang-javascript/dist/index.js',
			'@codemirror/language': '/node_modules/@codemirror/language/dist/index.js',
			'@codemirror/lint': '/node_modules/@codemirror/lint/dist/index.js',
			'@codemirror/search': '/node_modules/@codemirror/search/dist/index.js',
			'@codemirror/state': '/node_modules/@codemirror/state/dist/index.js',
			'@codemirror/theme-one-dark': '/node_modules/@codemirror/theme-one-dark/dist/index.js',
			'@codemirror/view': '/node_modules/@codemirror/view/dist/index.js',
			'@lezer/common': '/node_modules/@lezer/common/dist/index.js',
			'@lezer/css': '/node_modules/@lezer/css/dist/index.js',
			'@lezer/highlight': '/node_modules/@lezer/highlight/dist/index.js',
			'@lezer/html': '/node_modules/@lezer/html/dist/index.js',
			'@lezer/javascript': '/node_modules/@lezer/javascript/dist/index.js',
			'@lezer/lr': '/node_modules/@lezer/lr/dist/index.js',
			'@lume/element': '/node_modules/@lume/element/dist/index.js',
			'@uiw/codemirror-theme-noctis-lilac': '/node_modules/@uiw/codemirror-theme-noctis-lilac/esm/index.js',
			'@uiw/codemirror-themes': '/node_modules/@uiw/codemirror-themes/esm/index.js',
			'classy-solid': '/node_modules/classy-solid/dist/index.js',
			'code-mirror-el': '/dist/index.js',
			codemirror: '/node_modules/codemirror/dist/index.js',
			crelt: '/node_modules/crelt/index.js',
			'lodash-es/': '/node_modules/lodash-es/',
			lowclass: '/node_modules/lowclass/dist/index.js',
			'lowclass/': '/node_modules/lowclass/',
			'solid-js': '/node_modules/solid-js/dist/solid.js',
			'solid-js/html': '/node_modules/solid-js/html/dist/html.js',
			'solid-js/web': '/node_modules/solid-js/web/dist/web.js',
			'style-mod': '/node_modules/style-mod/src/style-mod.js',
			'thememirror/': '/node_modules/thememirror/',
			'w3c-keyname': '/node_modules/w3c-keyname/index.js',
		},
	},
}
